package com.stratagile.qlink.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BNB_WALLET".
*/
public class BnbWalletDao extends AbstractDao<BnbWallet, Long> {

    public static final String TABLENAME = "BNB_WALLET";

    /**
     * Properties of entity BnbWallet.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Address = new Property(1, String.class, "address", false, "ADDRESS");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Mnemonic = new Property(3, String.class, "mnemonic", false, "MNEMONIC");
        public final static Property IsCurrent = new Property(4, boolean.class, "isCurrent", false, "IS_CURRENT");
        public final static Property IsBackup = new Property(5, boolean.class, "isBackup", false, "IS_BACKUP");
        public final static Property IsLook = new Property(6, boolean.class, "isLook", false, "IS_LOOK");
        public final static Property PrivateKey = new Property(7, String.class, "privateKey", false, "PRIVATE_KEY");
        public final static Property PublicKey = new Property(8, String.class, "publicKey", false, "PUBLIC_KEY");
    }


    public BnbWalletDao(DaoConfig config) {
        super(config);
    }
    
    public BnbWalletDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BNB_WALLET\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ADDRESS\" TEXT," + // 1: address
                "\"NAME\" TEXT," + // 2: name
                "\"MNEMONIC\" TEXT," + // 3: mnemonic
                "\"IS_CURRENT\" INTEGER NOT NULL ," + // 4: isCurrent
                "\"IS_BACKUP\" INTEGER NOT NULL ," + // 5: isBackup
                "\"IS_LOOK\" INTEGER NOT NULL ," + // 6: isLook
                "\"PRIVATE_KEY\" TEXT," + // 7: privateKey
                "\"PUBLIC_KEY\" TEXT);"); // 8: publicKey
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BNB_WALLET\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BnbWallet entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(2, address);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String mnemonic = entity.getMnemonic();
        if (mnemonic != null) {
            stmt.bindString(4, mnemonic);
        }
        stmt.bindLong(5, entity.getIsCurrent() ? 1L: 0L);
        stmt.bindLong(6, entity.getIsBackup() ? 1L: 0L);
        stmt.bindLong(7, entity.getIsLook() ? 1L: 0L);
 
        String privateKey = entity.getPrivateKey();
        if (privateKey != null) {
            stmt.bindString(8, privateKey);
        }
 
        String publicKey = entity.getPublicKey();
        if (publicKey != null) {
            stmt.bindString(9, publicKey);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BnbWallet entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(2, address);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String mnemonic = entity.getMnemonic();
        if (mnemonic != null) {
            stmt.bindString(4, mnemonic);
        }
        stmt.bindLong(5, entity.getIsCurrent() ? 1L: 0L);
        stmt.bindLong(6, entity.getIsBackup() ? 1L: 0L);
        stmt.bindLong(7, entity.getIsLook() ? 1L: 0L);
 
        String privateKey = entity.getPrivateKey();
        if (privateKey != null) {
            stmt.bindString(8, privateKey);
        }
 
        String publicKey = entity.getPublicKey();
        if (publicKey != null) {
            stmt.bindString(9, publicKey);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BnbWallet readEntity(Cursor cursor, int offset) {
        BnbWallet entity = new BnbWallet( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // address
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // mnemonic
            cursor.getShort(offset + 4) != 0, // isCurrent
            cursor.getShort(offset + 5) != 0, // isBackup
            cursor.getShort(offset + 6) != 0, // isLook
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // privateKey
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // publicKey
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BnbWallet entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAddress(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMnemonic(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIsCurrent(cursor.getShort(offset + 4) != 0);
        entity.setIsBackup(cursor.getShort(offset + 5) != 0);
        entity.setIsLook(cursor.getShort(offset + 6) != 0);
        entity.setPrivateKey(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPublicKey(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BnbWallet entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BnbWallet entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BnbWallet entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
