package com.stratagile.qlink.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BTC_WALLET".
*/
public class BtcWalletDao extends AbstractDao<BtcWallet, Long> {

    public static final String TABLENAME = "BTC_WALLET";

    /**
     * Properties of entity BtcWallet.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property I = new Property(1, Long.class, "i", false, "I");
        public final static Property HexPrivateKey = new Property(2, String.class, "hexPrivateKey", false, "HEX_PRIVATE_KEY");
        public final static Property PublicKey = new Property(3, String.class, "publicKey", false, "PUBLIC_KEY");
        public final static Property WifPrivateKey = new Property(4, String.class, "wifPrivateKey", false, "WIF_PRIVATE_KEY");
        public final static Property Address = new Property(5, String.class, "address", false, "ADDRESS");
        public final static Property Name = new Property(6, String.class, "name", false, "NAME");
        public final static Property IsBackup = new Property(7, boolean.class, "isBackup", false, "IS_BACKUP");
        public final static Property IsCurrent = new Property(8, boolean.class, "isCurrent", false, "IS_CURRENT");
        public final static Property BigIntegerPrivateKey = new Property(9, String.class, "bigIntegerPrivateKey", false, "BIG_INTEGER_PRIVATE_KEY");
    }


    public BtcWalletDao(DaoConfig config) {
        super(config);
    }
    
    public BtcWalletDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BTC_WALLET\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"I\" INTEGER," + // 1: i
                "\"HEX_PRIVATE_KEY\" TEXT," + // 2: hexPrivateKey
                "\"PUBLIC_KEY\" TEXT," + // 3: publicKey
                "\"WIF_PRIVATE_KEY\" TEXT," + // 4: wifPrivateKey
                "\"ADDRESS\" TEXT," + // 5: address
                "\"NAME\" TEXT," + // 6: name
                "\"IS_BACKUP\" INTEGER NOT NULL ," + // 7: isBackup
                "\"IS_CURRENT\" INTEGER NOT NULL ," + // 8: isCurrent
                "\"BIG_INTEGER_PRIVATE_KEY\" TEXT);"); // 9: bigIntegerPrivateKey
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BTC_WALLET\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BtcWallet entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long i = entity.getI();
        if (i != null) {
            stmt.bindLong(2, i);
        }
 
        String hexPrivateKey = entity.getHexPrivateKey();
        if (hexPrivateKey != null) {
            stmt.bindString(3, hexPrivateKey);
        }
 
        String publicKey = entity.getPublicKey();
        if (publicKey != null) {
            stmt.bindString(4, publicKey);
        }
 
        String wifPrivateKey = entity.getWifPrivateKey();
        if (wifPrivateKey != null) {
            stmt.bindString(5, wifPrivateKey);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(6, address);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(7, name);
        }
        stmt.bindLong(8, entity.getIsBackup() ? 1L: 0L);
        stmt.bindLong(9, entity.getIsCurrent() ? 1L: 0L);
 
        String bigIntegerPrivateKey = entity.getBigIntegerPrivateKey();
        if (bigIntegerPrivateKey != null) {
            stmt.bindString(10, bigIntegerPrivateKey);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BtcWallet entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long i = entity.getI();
        if (i != null) {
            stmt.bindLong(2, i);
        }
 
        String hexPrivateKey = entity.getHexPrivateKey();
        if (hexPrivateKey != null) {
            stmt.bindString(3, hexPrivateKey);
        }
 
        String publicKey = entity.getPublicKey();
        if (publicKey != null) {
            stmt.bindString(4, publicKey);
        }
 
        String wifPrivateKey = entity.getWifPrivateKey();
        if (wifPrivateKey != null) {
            stmt.bindString(5, wifPrivateKey);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(6, address);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(7, name);
        }
        stmt.bindLong(8, entity.getIsBackup() ? 1L: 0L);
        stmt.bindLong(9, entity.getIsCurrent() ? 1L: 0L);
 
        String bigIntegerPrivateKey = entity.getBigIntegerPrivateKey();
        if (bigIntegerPrivateKey != null) {
            stmt.bindString(10, bigIntegerPrivateKey);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BtcWallet readEntity(Cursor cursor, int offset) {
        BtcWallet entity = new BtcWallet( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // i
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // hexPrivateKey
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // publicKey
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // wifPrivateKey
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // address
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // name
            cursor.getShort(offset + 7) != 0, // isBackup
            cursor.getShort(offset + 8) != 0, // isCurrent
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9) // bigIntegerPrivateKey
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BtcWallet entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setI(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setHexPrivateKey(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPublicKey(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setWifPrivateKey(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAddress(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setIsBackup(cursor.getShort(offset + 7) != 0);
        entity.setIsCurrent(cursor.getShort(offset + 8) != 0);
        entity.setBigIntegerPrivateKey(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BtcWallet entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BtcWallet entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BtcWallet entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
