package com.stratagile.qlink.db;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 87): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 87;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        BnbWalletDao.createTable(db, ifNotExists);
        BtcWalletDao.createTable(db, ifNotExists);
        BuySellBuyTodoDao.createTable(db, ifNotExists);
        BuySellSellTodoDao.createTable(db, ifNotExists);
        DefiSearchHistoryDao.createTable(db, ifNotExists);
        DWCSessionDao.createTable(db, ifNotExists);
        EntrustTodoDao.createTable(db, ifNotExists);
        EosAccountDao.createTable(db, ifNotExists);
        EthWalletDao.createTable(db, ifNotExists);
        QLCAccountDao.createTable(db, ifNotExists);
        RecordSaveDao.createTable(db, ifNotExists);
        SwapRecordDao.createTable(db, ifNotExists);
        TopupTodoListDao.createTable(db, ifNotExists);
        TransactionRecordDao.createTable(db, ifNotExists);
        UserAccountDao.createTable(db, ifNotExists);
        VpnEntityDao.createTable(db, ifNotExists);
        VpnServerRecordDao.createTable(db, ifNotExists);
        WalletDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        BnbWalletDao.dropTable(db, ifExists);
        BtcWalletDao.dropTable(db, ifExists);
        BuySellBuyTodoDao.dropTable(db, ifExists);
        BuySellSellTodoDao.dropTable(db, ifExists);
        DefiSearchHistoryDao.dropTable(db, ifExists);
        DWCSessionDao.dropTable(db, ifExists);
        EntrustTodoDao.dropTable(db, ifExists);
        EosAccountDao.dropTable(db, ifExists);
        EthWalletDao.dropTable(db, ifExists);
        QLCAccountDao.dropTable(db, ifExists);
        RecordSaveDao.dropTable(db, ifExists);
        SwapRecordDao.dropTable(db, ifExists);
        TopupTodoListDao.dropTable(db, ifExists);
        TransactionRecordDao.dropTable(db, ifExists);
        UserAccountDao.dropTable(db, ifExists);
        VpnEntityDao.dropTable(db, ifExists);
        VpnServerRecordDao.dropTable(db, ifExists);
        WalletDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(BnbWalletDao.class);
        registerDaoClass(BtcWalletDao.class);
        registerDaoClass(BuySellBuyTodoDao.class);
        registerDaoClass(BuySellSellTodoDao.class);
        registerDaoClass(DefiSearchHistoryDao.class);
        registerDaoClass(DWCSessionDao.class);
        registerDaoClass(EntrustTodoDao.class);
        registerDaoClass(EosAccountDao.class);
        registerDaoClass(EthWalletDao.class);
        registerDaoClass(QLCAccountDao.class);
        registerDaoClass(RecordSaveDao.class);
        registerDaoClass(SwapRecordDao.class);
        registerDaoClass(TopupTodoListDao.class);
        registerDaoClass(TransactionRecordDao.class);
        registerDaoClass(UserAccountDao.class);
        registerDaoClass(VpnEntityDao.class);
        registerDaoClass(VpnServerRecordDao.class);
        registerDaoClass(WalletDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
